kind: analysis
title: 26 - Ridership in Multivariate OTP Model
group: Ridership and External Factors
tables:
- Analysis
- otp_monthly
- paired
- pathlib
- prt_otp_analysis
- ridership_monthly
- route_stops
- routes
- scipy
- stops
files: []
analyses: []
